- hosts: "masters, workers"
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
     - name: remove docker
       shell: |
               sudo apt-get purge -y docker-engine docker docker.io docker-ce docker-ce-cli
               sudo apt-get autoremove -y --purge docker-engine docker docker.io docker-ce
               sudo rm -rf /var/lib/docker /etc/docker
               sudo rm /etc/apparmor.d/docker
               sudo groupdel docker
               sudo rm -rf /var/run/docker.sock
